#Experiment configuration file.

_spatial_dim: &spatial_dim 3
_num_points: &num_points 44121
_out0: &out0 4096 #1000
_out1: &out1 512 #125
_latent_dim: &latent_dim 100 #10

#Model arguments
spatial_dim: *spatial_dim #int
latent_dim: *latent_dim #int
point_seq: [*num_points, *out0] #[int]
quad_map: "param_quad" #str <function in quadrature.py>
stages: 1 #int
loss_fn: "MSELoss" #str, loss from torch.nn
optimizer: "Adam" #str, optimizer from torch.optim
learning_rate: 0.001 #0.01 #float
weight_activation: "Sigmoid" #str <function in torch.nn>
normalize_weights: False #bool
output_activation: "Identity" # str, activation from torch.nn (Identity, Tanh)

conv_params:
  in_points: [*num_points, *out0] #list[int]
  out_points: [*out0, *out1] #list[int]
  in_channels: [4, 16] # [4, 16] #list[int]
  out_channels: [16, 16] #[16, 16] #list[int]
  bias: [True] #[False] #[bool]
  filter_seq: [[16, 16, 16]] #[[int]]
  filter_mode: [single] #[string] <single|share_in|nested>
  decay_param: [100000] #[float]
