# General run config
ppn: 1 # integer - number of MPI processes per node for ML training
ppd: 1 # integer - number of MPI processes per device for ML training
logging: "debug" # no, debug, verbose-perf - type of logging desired
device: "cpu" # cpu, cuda, xpu - device to train on
distributed: "ddp" # horovod, ddp - distributed training library
model: "sgs" # sgs, qcnn-3d - model ID
data_path: "synthetic" # string, synthetic - path to training data to load
repeatability: False # True, False - make training deterministic

# Training hyperparameters config
epochs: 10 # integer - max number of epochs for training
mini_batch: 1 # integer - mini batch size for SGD update
learning_rate: 0.001 # float - serial leranring rate
tolerance: 1.0e-8 # float - convergence tolerance of validation loss
validation_split: 0.20 # float - percentage of data kept for validation
optimizer: "Adam" # Adam - optimizer used for training
scheduler: "None" # None,Plateau - optimizer scheduler to be used
precision: "fp32" # fp32,fp64,bf16,tf32 - precision for training
name: "./NNmodel" # string - name used to save ML model
save_db: False # True, False - save database contents at the end of trainint to .rdb file

# Online train config
online:
    db_launch: "" # colocated,clustered - deployment method of SmartSim database
    batch: 0 # integer - number of tensors to grab from database at once, 0: grab all tensors at once. For online ML only!
    simprocs: 1 # int - number of MPI processes simulation is running with
    db_nodes: 1 # int - number of nodes dabase is sharded across
 
# Model specific config
sgs:
    neurons: 20 # integer - number of neurons in layers for SGS model
    layers: 1 # integer - number of hidden layers for SGS model
    comp_model_ins_outs: False # True, False - compute the model inputs and outputs from raw data
qcnn: 
    mesh_file: "" # string - path to mesh nodes for QCNN model
    channels: 4 # integer - channels for QCNN model
    qcnn_config: "" # string - path to config file for QCNN model
    

