# QuadConv model configuration file
_spatial_dim: &spatial_dim 2
_num_points: &num_points 2189
_out0: &out0 2500
_out1: &out1 625
_latent_dim: &latent_dim 50

# Model arguments
module: "pool" #str <skip|pool>_coder
spatial_dim: *spatial_dim #int
latent_dim: *latent_dim #int
point_seq: [*num_points, *out0] #[int]
quad_map: "param_quad" #str <function in quadrature.py>
quad_args: {} #dict
stages: 1 #int
output_activation: "Tanh" #str, <activation in torch.nn>
internal_activation: "ReLU" #str, <activation in torch.nn>, CELU, GELU, ReLU
loss_fn: "RRELoss" #str, <loss in torch_compression.loss|loss in torch.nn>
noise_scale: 0.0 #float
load_mesh_weights: [True]

conv_params:
  in_points: [*num_points, *out0] #list[int]
  out_points: [*out0, *out1] #list[int]
  in_channels: [4, 16] #list[int]
  out_channels: [16, 16] #list[int]
  bias: [False] #[bool]
  filter_seq: [[16, 16, 16]] #[[int]]
  filter_mode: [single] #[string] <single|share_in|nested>
  decay_param: [null] #[float]
  verbose: [False]
